# This file gives the config defaults for all experiments.

#============================================

# RTT Experiment
# These parameters are the ones that are designed t be changed. there are others, hardcoded in the script

local_test: True  # For testing the RTT script locally, with iperf -c 127.0.0.1
rtt_experiment_time: 10  # Clients send for this many seconds
genfolder: /etc/scion/gen/ # Used to find neighbors / findtopo

rtt_measurement_interface: lo  # Will not be used if 'local_test'= True

neighbors_file: neighbors.txt
processes_file: processes.txt
perf_record_file: temp.perf.data
perf_dump_file: perf.log
parsed_destination: perf.csv
iperf_log: iperf_output.log

rtt_hosts:
    scionlab-1007-rtt: 122.248.221.20
    scionlab-1004-rtt: 3.12.159.15
    scionlab-1102-rtt: 129.132.121.187

iperf_port_start: 51000
iperf_port_end: 65535
#=============================================

# Flowtele experiment
name: 'default_experiment'


# Experiment Parameters

use_scion: True
use_shaping: True
num_flows: 2

# Host Adresses and roles

hosts:
    scionlab-1007-rtt:
        ip: 122.248.221.20
        ia: 16-ffaa:0:1007
        local_ip: 172.31.27.114
        scionaddr: 16-ffaa:0:1007,[172.31.27.114]
        location: Singapore
    scionlab-1004-rtt:
        ip: 3.12.159.15
        ia: 16-ffaa:0:1004
        local_ip: 172.31.2.128
        scionaddr: 16-ffaa:0:1004,[172.31.2.128]
        location: Ohio
    scionlab-1102-rtt:
        ip: 129.132.121.187
        ia: 17-ffaa:0:1102
        local_ip: 129.132.121.187
        scionaddr: 17-ffaa:0:1102,[129.132.121.187] #unused at the moment
        location: CAB

hostname_label_map:
    scionlab-1007-rtt: h1
    scionlab-1004-rtt: h2
    scionlab-1102-rtt: m
    james-linux-host: tester

label_role_map:
    h1: receiver
    h2: off
    m: sender
    tester: tester


# Network Parameters

local_port_start_range: 6000
listener_port: 5500
tshark_net_interface: 'lo'


# Source locations

scion_location: '/home/james/go/src/github.com/scionproto/scion'

valloc_python_command: "pyhton2"
valloc_location: '/home/james/bitbucket/csl331/vAlloc/vAlloc.py'

athena_python_command: "pyhton3.6"
atchena_location: '/home/james/bitbucket/csl331/dbus/athena_m2.py'

ftsocket_location: '/home/james/go/src/github.com/scionproto/scion/bazel-bin/go/flowtele/linux_amd64_stripped/flowtele_socket'
quic_listener_location: '/home/james/go/src/github.com/scionproto/scion/bazel-bin/go/flowtele/listener/linux_amd64_stripped/flowtele_listener'

print_to_console: True

tshark_suffix: '_tshark.log'
fshaper_suffix: '_fshaper.log'
athena_suffix: '_athena.log'

flow_suffix: '_flow.log'
quicrecv_suffix: '_quicrecv.log'

this_hostname: default_host

# Resultfile Locations
# Is inferred. Setting result dir and executing with flowtele-experiment.py will have no effect
result_dir:
tshark_dump:
fshaper_log:


# Timing
sender_delay_time: 2
send_duration: 10 # In seconds
calibrator_duration: 2

# Postprocessing
truncate_front: 2
truncate_back: 2

# If a metric is not set to be plotted, it also might not be measured at all.
plot_loss: True
plot_throughput: True
plot_cwnd: False     # Automatically overridden to false if not TCP
plot_latency: True
plot_queue: True
plot_memory: False
plot_iperf_losslat: False

stats_file: stats.json

inferred:
    behavior_summary:
    bw_delay_product: # unit: number of Packets of 1514B
    cbr_rate:
    num_senders:



